// lib/comune-content.ts
// Contenuti variabili per comune per evitare thin content

export interface ComuneContent {
  prezzoMq: number;
  esempioMq: number;
  esempioPrezzo: number;
  durataCantiere: string;
  durataRange: string;
  tagHero: string[];
  testoIntro: string;
  testoCosti: string;
  immagineHero: string;
  noteCantiere: string[];
}

// ─────────────────────────────────────────────
// PREZZI PER ZONA
// Agro Aversano: 550 €/mq
// Caserta/Provincia: 550 €/mq
// Napoli/Provincia: 550 €/mq
// ─────────────────────────────────────────────

const contenutiBase: Record<string, Partial<ComuneContent>> = {
  // ZONA: NAPOLI / PROVINCIA — 550 €/mq
  napoli: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "8–14 settimane",
    durataRange: "8–14",
    tagHero: ["Preventivo immediato", "Sopralluogo tecnico", "Costo trasparente", "Chiavi in mano"],
    testoIntro: "Devi ristrutturare casa a Napoli? Ristrutturiamo il tuo appartamento completo a partire da 550 €/mq. Compila i campi, scopri immediatamente il costo della tua ristrutturazione e ricevi il tuo preventivo.",
    testoCosti: "Il costo reale dipende soprattutto da metratura, stato degli impianti, accessibilità del cantiere e livello delle finiture. Il preventivo online è una prima stima utile, mentre il prezzo definitivo si conferma dopo sopralluogo tecnico.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Accesso e logistica in centro possono allungare i tempi", "Smaltimento macerie e permessi condominiali da verificare", "Impianti vecchi e distribuzioni interne da controllare prima del preventivo"],
  },
  "giugliano-in-campania": {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–12 settimane",
    durataRange: "7–12",
    tagHero: ["Prezzario Regione Campania", "Napoli Nord", "Bonus 50% applicabile", "Espansione residenziale"],
    testoIntro: "Giugliano in Campania è uno dei comuni più popolosi della provincia di Napoli, con un tessuto edilizio in forte espansione e una mescolanza di palazzine storiche e nuovi condomini.",
    testoCosti: "I costi a Giugliano in Campania sono in linea con la provincia di Napoli, con buona disponibilità di maestranze e logistica semplificata rispetto al centro di Napoli.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Espansione residenziale: verificare regolarità edilizia", "Palazzine anni '70-'80: amianto frequente", "Traffico intenso: pianificare orari di cantiere"],
  },
  "melito-di-napoli": {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–12 settimane",
    durataRange: "7–12",
    tagHero: ["Prezzario Regione Campania", "Napoli Nord", "Bonus 50% applicabile", "Palazzine e condomini"],
    testoIntro: "Melito di Napoli è un comune densamente popolato dell'area nord di Napoli, caratterizzato da un tessuto edilizio prevalentemente residenziale con palazzine degli anni '60-'80.",
    testoCosti: "I costi a Melito di Napoli sono in linea con la provincia di Napoli. La densità abitativa e la logistica influenzano i tempi di cantiere più dei costi materiali.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '60-'80: verificare amianto e umidità", "Densità abitativa: coordinare accesso e orari con il condominio", "Parcheggio limitato: pianificare logistica materiali"],
  },
  "mugnano-di-napoli": {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–12 settimane",
    durataRange: "7–12",
    tagHero: ["Prezzario Regione Campania", "Napoli Nord", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Mugnano di Napoli è un comune residenziale dell'area nord della provincia, con un tessuto edilizio composto da palazzine degli anni '70-'80 e zone di espansione più recente.",
    testoCosti: "I costi a Mugnano di Napoli sono in linea con la media della provincia di Napoli. La posizione strategica rispetto all'asse di collegamento con Caserta rende il comune ben servito da maestranze.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70: amianto nelle canne fumarie", "Espansione recente: verificare regolarità edilizia", "Posizione strategica: logistica agevole"],
  },
  casandrino: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–12 settimane",
    durataRange: "7–12",
    tagHero: ["Prezzario Regione Campania", "Napoli Nord", "Bonus 50% applicabile", "Palazzine anni '60-'80"],
    testoIntro: "Casandrino è un comune dell'area nord di Napoli con un tessuto edilizio prevalentemente composto da palazzine degli anni '60-'80 e alcune zone di espansione recente.",
    testoCosti: "I costi a Casandrino sono in linea con la provincia di Napoli. La prossimità a Napoli e Giugliano ne fa un comune a forte vocazione residenziale con prezzi di mercato stabili.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Canne fumarie in amianto nei condomini anni '60-'70", "Umidità di risalita nei piani terra", "Impianti condominiali obsoleti nelle palazzine più vecchie"],
  },
  "grumo-nevano": {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–12 settimane",
    durataRange: "7–12",
    tagHero: ["Prezzario Regione Campania", "Confine Caserta", "Bonus 50% applicabile", "Palazzine e villette"],
    testoIntro: "Grumo Nevano è un comune al confine tra la provincia di Napoli e quella di Caserta, con un tessuto edilizio ibrido che mescola caratteristiche di entrambe le aree.",
    testoCosti: "I costi a Grumo Nevano sono in linea con la provincia di Napoli. La posizione di confine offre vantaggi logistici e una buona disponibilità di maestranze da entrambe le province.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Posizione di confine: maestranze disponibili da Napoli e Caserta", "Palazzine anni '70: tubazioni in acciaio zincato", "Umidità di risalita nei piani terra"],
  },
  "sant-antimo": {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–12 settimane",
    durataRange: "7–12",
    tagHero: ["Prezzario Regione Campania", "Napoli Nord", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Sant'Antimo è un comune dell'area nord di Napoli con un tessuto edilizio prevalentemente residenziale, caratterizzato da palazzine degli anni '70-'80 e zone di espansione più recente.",
    testoCosti: "I costi a Sant'Antimo sono in linea con la media della provincia di Napoli. La densità abitativa e la vicinanza ai centri maggiori rendono il comune ben servito.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70-'80: verificare amianto e impianti", "Densità abitativa: coordinare accesso cantiere", "Espansione recente: verificare regolarità edilizia"],
  },

  // ZONA: CASERTA / PROVINCIA — 550 €/mq
  caserta: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–11 settimane",
    durataRange: "7–11",
    tagHero: ["Prezzario Regione Campania", "Centro storico e periferia", "Bonus 50% applicabile", "Vicinanza Reggia"],
    testoIntro: "Per ristrutturare casa o appartamento a Caserta conviene partire da un preventivo dettagliato, costruito sulle condizioni reali dell'immobile e sugli interventi desiderati. Una ristrutturazione completa può includere demolizioni, smaltimento macerie, modifica degli ambienti, rifacimento degli impianti, massetti, pavimenti, rivestimenti, tinteggiature e montaggi finali. Il sopralluogo tecnico permette di stabilire quali lavorazioni servono davvero e di organizzare il cantiere con un unico referente.",
    testoCosti: "Il costo della ristrutturazione a Caserta parte da 550 €/mq per un intervento completo standard, ma il prezzo finale dipende da metratura, stato degli impianti, opere murarie, livello delle finiture, accessibilità e lavorazioni richieste per bagno e cucina. Il preventivo online offre una prima indicazione; l'importo definitivo viene confermato dopo il sopralluogo, con lavorazioni, materiali, tempi e condizioni riportati in modo chiaro.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Impianti esistenti: verificarne stato e adeguamenti necessari", "Bagno e cucina: definire prima spostamenti, scarichi e finiture", "Accesso al cantiere: organizzare consegne, demolizioni e smaltimento"],
  },
  marcianise: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–11 settimane",
    durataRange: "7–11",
    tagHero: ["Prezzario Regione Campania", "Area industriale", "Bonus 50% applicabile", "Palazzine e villette"],
    testoIntro: "Marcianise è un comune con una forte componente industriale e commerciale, ma con un nucleo residenziale significativo composto da palazzine degli anni '60-'80 nel centro e villette nelle zone periferiche.",
    testoCosti: "I costi a Marcianise sono in linea con la provincia di Caserta. La prossimità all'autostrada e al casello A30 ha favorito l'espansione residenziale con prezzi di mercato competitivi.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Vibrazioni da traffico sulla SS7: verificare lesioni muri", "Palazzine anni '60-'70: amianto e umidità", "Espansione residenziale: verificare regolarità edilizia"],
  },
  curti: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–11 settimane",
    durataRange: "7–11",
    tagHero: ["Prezzario Regione Campania", "Caserta Nord", "Bonus 50% applicabile", "Palazzine e villette"],
    testoIntro: "Curti è un comune di dimensioni ridotte nella provincia di Caserta, con un tessuto edilizio prevalentemente residenziale composto da palazzine degli anni '70-'80 e villette degli anni '90-2000.",
    testoCosti: "I costi a Curti sono in linea con la provincia di Caserta. La posizione tra Caserta e Marcianise lo rende un comune a forte domanda abitativa con prezzi stabili.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70: tubazioni in acciaio zincato", "Umidità di risalita nei piani terra", "Villette anni '90: verificare stato coperture"],
  },
  "santa-maria-capua-vetere": {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–11 settimane",
    durataRange: "7–11",
    tagHero: ["Prezzario Regione Campania", "Centro storico romano", "Bonus 50% applicabile", "Vincoli archeologici"],
    testoIntro: "Santa Maria Capua Vetere è un comune di rilevanza storica, sede dell'antica Capua romana, con un centro storico ricco di reperti e vincoli archeologici.",
    testoCosti: "I costi a Santa Maria Capua Vetere sono in linea con la provincia di Caserta. Il centro storico richiede attenzioni specifiche per i vincoli archeologici del sottosuolo.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Vincoli archeologici: verificare mappa sottosuolo prima di scavi", "Umidità da falde acquifere superficiali nel centro", "Palazzine anni '60-'70: amianto e impianti obsoleti"],
  },
  casapulla: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–11 settimane",
    durataRange: "7–11",
    tagHero: ["Prezzario Regione Campania", "Caserta Nord", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Casapulla è un comune della provincia di Caserta con un tessuto edilizio prevalentemente residenziale, composto da palazzine degli anni '70-'80 e villette degli anni '90.",
    testoCosti: "I costi a Casapulla sono in linea con la provincia di Caserta. La posizione favorevole rispetto ai principali centri rende il comune attrattivo per la ristrutturazione.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70: amianto nelle canne fumarie", "Umidità di risalita nei piani terra", "Villette anni '90: verificare regolarità edilizia"],
  },
  recale: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–11 settimane",
    durataRange: "7–11",
    tagHero: ["Prezzario Regione Campania", "Caserta Nord", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Recale è un comune residenziale della provincia di Caserta, con un tessuto edilizio composto principalmente da palazzine degli anni '70-'80 e villette degli anni '90-2000.",
    testoCosti: "I costi a Recale sono in linea con la provincia di Caserta. La prossimità a Caserta lo rende un polo residenziale attrattivo con prezzi di mercato stabili.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70: amianto e impianti obsoleti", "Umidità di risalita nei piani terra", "Villette anni '90: verificare stato coperture e isolamento"],
  },
  "san-prisco": {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–11 settimane",
    durataRange: "7–11",
    tagHero: ["Prezzario Regione Campania", "Caserta Nord", "Bonus 50% applicabile", "Residenziale storico"],
    testoIntro: "San Prisco è un comune della provincia di Caserta con un tessuto edilizio prevalentemente residenziale, che ospita la Cattedrale paleocristiana di San Prisco.",
    testoCosti: "I costi a San Prisco sono in linea con la provincia di Caserta. Il nucleo storico e le zone di espansione offrono un mix di edilizia che richiede approcci diversi.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70: amianto e tubazioni obsolete", "Umidità di risalita nei piani terra", "Espansione privata: verificare regolarità edilizia"],
  },
  capua: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–11 settimane",
    durataRange: "7–11",
    tagHero: ["Prezzario Regione Campania", "Centro storico medievale", "Bonus 50% applicabile", "Vicinanza Volturno"],
    testoIntro: "Capua è un comune con un centro storico di origine medievale ben conservato, circondato dalle anse del Volturno. Il tessuto edilizio mescola edifici storici e palazzine moderne.",
    testoCosti: "I costi a Capua sono in linea con la provincia di Caserta. Il centro storico richiede attenzioni per l'umidità da risalita, accentuata dalla vicinanza al fiume Volturno.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Centro storico: umidità da risalita accentuata dal Volturno", "Vincoli Soprintendenza per facciate ed elementi storici", "Palazzine anni '70: amianto e impianti datati"],
  },
  casagiove: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "7–11 settimane",
    durataRange: "7–11",
    tagHero: ["Prezzario Regione Campania", "Caserta Nord", "Bonus 50% applicabile", "Villette e palazzine"],
    testoIntro: "Casagiove è un comune residenziale adiacente a Caserta, con un tenore abitativo mediamente più elevato. Il tessuto edilizio comprende villette e palazzine di qualità costruttiva superiore.",
    testoCosti: "I costi a Casagiove sono in linea con la provincia di Caserta. La presenza di villette con doppio bagno e spazi ampi può far crescere il budget totale, ma il costo al mq resta nella media.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Villette anni '80: verificare guaine e coperture piane", "Palazzine anni '70: tubazioni in acciaio zincato", "Aperture cucina-soggiorno: verificare natura muro divisorio"],
  },

  // ZONA: AGRO AVERSANO — 550 €/mq
  aversa: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Palazzine e villette"],
    testoIntro: "Devi ristrutturare casa a Aversa? La nostra impresa di ristrutturazioni segue ogni fase della ristrutturazione completa del tuo appartamento: demolizioni, impianti, opere murarie, pavimenti, rivestimenti, tinteggiature e finiture. Partiamo da 550 €/mq per darti subito un riferimento chiaro sul costo ristrutturazione a Aversa, poi definiamo un preventivo dettagliato dopo aver visto l'immobile.",
    testoCosti: "Il costo di ristrutturazione di un appartamento a Aversa varia in base a metratura, stato degli impianti, distribuzione interna e livello delle finiture. Il preventivo online ti dà una prima stima indicativa del prezzo, mentre il preventivo definitivo per la tua ristrutturazione viene confermato dopo sopralluogo tecnico, con tutte le lavorazioni necessarie esplicitate.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: [],
  },
  lusciano: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Lusciano è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, caratterizzato da palazzine degli anni '70-'80 e zone di espansione più recente.",
    testoCosti: "I costi a Lusciano sono in linea con l'Agro Aversano, leggermente inferiori alla media campana. La posizione centrale rispetto alla zona rende il comune ben servito da maestranze.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70-'80: amianto e umidità", "Espansione recente: verificare regolarità edilizia", "Posizione centrale: logistica agevole"],
  },
  carinaro: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Carinaro è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, composto da palazzine degli anni '70-'80 e villette nelle zone periferiche.",
    testoCosti: "I costi a Carinaro sono in linea con l'Agro Aversano. La prossimità ad Aversa e alla SS7 rende il comune ben collegato e servito da maestranze locali.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70: amianto e impianti obsoleti", "Umidità di risalita nei piani terra", "Prossimità SS7: possibili vibrazioni da traffico"],
  },
  "casal-di-principe": {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Casal di Principe è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, caratterizzato da palazzine degli anni '70-'80 e zone di espansione.",
    testoCosti: "I costi a Casal di Principe sono in linea con l'Agro Aversano. La densità abitativa e la logistica influenzano i tempi di cantiere più dei costi materiali.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70-'80: verificare amianto e umidità", "Espansione residenziale: verificare regolarità edilizia", "Densità abitativa: coordinare accesso cantiere"],
  },
  casaluce: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Casaluce è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, composto da palazzine degli anni '70-'80 e zone di espansione più recente.",
    testoCosti: "I costi a Casaluce sono in linea con l'Agro Aversano. La posizione strategica nella zona rende il comune ben servito da maestranze locali.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70: amianto nelle canne fumarie", "Umidità di risalita nei piani terra", "Espansione recente: verificare regolarità edilizia"],
  },
  cesa: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Cesa è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, caratterizzato da palazzine degli anni '70-'80 e villette nelle zone periferiche.",
    testoCosti: "I costi a Cesa sono in linea con l'Agro Aversano. La prossimità ad Aversa e alla rete viaria principale rende il comune ben collegato.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70-'80: amianto e impianti obsoleti", "Villette: verificare stato coperture e isolamento", "Prossimità Aversa: logistica agevole"],
  },
  frignano: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Frignano è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, composto da palazzine degli anni '70-'80 e zone di espansione.",
    testoCosti: "I costi a Frignano sono in linea con l'Agro Aversano. La posizione nella zona rende il comune attrattivo per la ristrutturazione con prezzi competitivi.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70: amianto e umidità", "Espansione residenziale: verificare regolarità edilizia", "Logistica semplificata rispetto ai grandi centri"],
  },
  "gricignano-di-aversa": {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Gricignano di Aversa è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, caratterizzato da palazzine degli anni '70-'80.",
    testoCosti: "I costi a Gricignano di Aversa sono in linea con l'Agro Aversano. La prossimità alla base NATO e alla rete viaria rende il comune ben collegato.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70-'80: amianto e impianti obsoleti", "Prossimità base NATO: verificare eventuali vincoli", "Logistica agevole per accesso materiali"],
  },
  parete: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Parete è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, composto da palazzine degli anni '70-'80 e villette nelle zone periferiche.",
    testoCosti: "I costi a Parete sono in linea con l'Agro Aversano. La posizione nella zona rende il comune ben servito da maestranze locali.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70: amianto e umidità", "Villette: verificare stato coperture", "Logistica semplificata"],
  },
  teverola: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Teverola è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, caratterizzato da palazzine degli anni '70-'80 e zone di espansione.",
    testoCosti: "I costi a Teverola sono in linea con l'Agro Aversano. La prossimità ad Aversa e alla SS7 rende il comune ben collegato e servito.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70-'80: amianto e impianti obsoleti", "Espansione residenziale: verificare regolarità edilizia", "Prossimità SS7: possibili vibrazioni da traffico"],
  },
  "trentola-ducenta": {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Trentola Ducenta è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, composto da palazzine degli anni '70-'80 e villette.",
    testoCosti: "I costi a Trentola Ducenta sono in linea con l'Agro Aversano. La posizione nella zona rende il comune attrattivo per la ristrutturazione.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70: amianto e umidità", "Villette: verificare stato coperture e isolamento", "Logistica agevole"],
  },
  "villa-di-briano": {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Villa di Briano è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, caratterizzato da palazzine degli anni '70-'80.",
    testoCosti: "I costi a Villa di Briano sono in linea con l'Agro Aversano. La posizione nella zona rende il comune ben servito da maestranze locali.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70-'80: amianto e impianti obsoleti", "Umidità di risalita nei piani terra", "Logistica semplificata"],
  },
  villaricca: {
    prezzoMq: 550,
    esempioMq: 80,
    esempioPrezzo: 44000,
    durataCantiere: "6–10 settimane",
    durataRange: "6–10",
    tagHero: ["Prezzario Regione Campania", "Agro Aversano", "Bonus 50% applicabile", "Residenziale"],
    testoIntro: "Villaricca è un comune dell'Agro Aversano con un tessuto edilizio prevalentemente residenziale, composto da palazzine degli anni '70-'80 e villette nelle zone periferiche.",
    testoCosti: "I costi a Villaricca sono in linea con l'Agro Aversano. La prossimità a Napoli Nord rende il comune attrattivo con prezzi competitivi.",
    immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
    noteCantiere: ["Palazzine anni '70: amianto e umidità", "Villette: verificare stato coperture", "Prossimità Napoli: buona disponibilità maestranze"],
  },
};

// ─────────────────────────────────────────────
// DEFAULT per comuni non mappati esplicitamente
// ─────────────────────────────────────────────

const defaultContent: ComuneContent = {
  prezzoMq: 550,
  esempioMq: 80,
  esempioPrezzo: 44000,
  durataCantiere: "6–10 settimane",
  durataRange: "6–10",
  tagHero: ["Prezzario Regione Campania", "Lavori concordati", "Bonus 50% applicabile"],
  testoIntro: "La ristrutturazione completa di una casa o di un appartamento richiede una valutazione precisa dei lavori da eseguire, dei materiali da utilizzare e delle condizioni iniziali dell'immobile.",
  testoCosti: "Il prezzo di una ristrutturazione varia in base alla metratura dell'abitazione, allo stato degli impianti, alla distribuzione degli ambienti, alle finiture scelte e alla complessità degli interventi.",
  immagineHero: "/images/servizi/ristrutturazione-appartamento-completo.jpg",
  noteCantiere: ["Demolizioni e rimozioni: 3–5 gg", "Impianti elettrico, idraulico e termico: 7–10 gg"],
};

export function getComuneContent(slug: string): ComuneContent {
  return { ...defaultContent, ...contenutiBase[slug] };
}
